angular.module('yarn').directive('userInput', UserInputDirective);
angular.module('yarn').filter('rawHtml', ['$sce', function($sce){
    return function(val) {
        return $sce.trustAsHtml(val);
    };
}]);


function UserInputDirective() {
    return {
        restrict: 'E',
        bindToController: {
            text: '=',
            onFocus: '&',
            onEscapeFocus: '&',
            onSubmit: '&'
        },
        scope: {},
        controllerAs: 'userInput',
        templateUrl: './html/userInput.html',
        controller: UserInputController
    };

    function UserInputController($scope, $element, hotkeys) {
        var self = this;

        this.hasFocus = false;

        hotkeys.bindTo($scope)
            .add({
                combo: 'esc',
                allowIn: ['INPUT', 'SELECT', 'TEXTAREA'],
                description: 'Focus back to the editor',
                callback: function () {
                    self.toggleFocus();
                }
        });

        //todo: command definitions should be in a separate service
        this.getAutoCompleteMatches = function (searchText) {
            var commands = {
                "help" : {
                    display: "help",
                    autocomplete: "help",
                    description: "Show the list of available commands",
                },
                "help+command" : {
                    display: "help <em>command</em>",
                    autocomplete: "help ",
                    description: "Show help on a specific command"
                },
                "load": {
                    display: "load http://somewhere.com/some-file.yarn.txt",
                    autocomplete: "load http://",
                    descripton: "Load a new story from source files"
                },
                "inventory": {
                    display: "inventory",
                    autocomplete: "inventory",
                    descripton: "Show the inventory"
                },
                "state": {
                    display: "state",
                    autocomplete: "state",
                    descripton: "Show the game state"
                },
                "tree": {
                    display: "tree",
                    autocomplete: "tree",
                    descripton: "Show the <em>Abstract Syntax Tree</em> generated by the compiler"
                },
                "token": {
                    display: "token",
                    autocomplete: "token",
                    descripton: "Show how the compiler tokenized the source code (technical)"
                }
            };

            var results = [];

            angular.forEach(commands, function (command, key) {
                var isMatch = key.trim().indexOf(
                    searchText.trim()
                ) === 0;
                if (isMatch) results.push(command);
            });

            return results;
        };

        this.keypress = function (event) {
            if (event.keyCode === 13) {
                event.preventDefault();
                self.submit();
                this.focus();
            }
        };

        this.toggleFocus = function () {
            if (this.hasFocus) {
                this.blur();
            } else {
                this.focus();
            }
        };

        this.focus = function () {
            if (!this.hasFocus) {
                //console.log("console in!");
                $element.find("input")[0].focus();
                this.hasFocus = true;
                this.onFocus();
            }
        };

        this.blur = function () {
            if (this.hasFocus) {
                //console.log("console out!");
                $element.find("input")[0].blur();
                this.hasFocus = false;
                this.onEscapeFocus();
            }
        };

        this.submit = function () {
            //console.log("this.submit!!!", this.text);
            if (this.text.trim() !== "") {
                this.onSubmit({text: this.text});
                this.text = "";
            }
            this.focus();
        };
    }
}