angular.module('yarn').factory('treeCommand', treeCommand);

function treeCommand(yConsole,
                     game) {

    function handler() {
        var html = game.scripts[0].ast.html();
        yConsole.debug("Outputing execution tree:");
        yConsole.debug(html);
    }

    return {
        name: "tree",
        shortDescription: "Show the <em>Abstract Syntax Tree</em> generated by the compiler",
        longDescription: "Show the <em>Abstract Syntax Tree</em> generated by the compiler",
        handler: handler
    };

}